### PR TITLE
Add placholder images for products

### LINKED ISSUE #2: #INC-5312: Missing image
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

### PR DESCRIPTION
**Pull request by pinieb**
Adding placeholder images 

Screen Shot 2022-07-26 at 12 11 22 PM

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @pinieb, I'll review the changes right away!

**Review by vanessa-cooper — DISMISSED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by pinieb** [comment]
@vanessa-cooper Can you please take another look?

**Comment by pinieb** [comment]
Let's try reopening

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @pinieb! You're now able to merge the PR.

**Pull request merged**
